--revenue generated by each gender 
SELECT
    "Gender",
    SUM("Purchase Amount (USD)") AS total_sales
FROM customer
GROUP BY "Gender";



--which customers used a discount still spent more than an average customer
SELECT 
    "Customer ID",
    "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >
    (SELECT AVG("Purchase Amount (USD)") FROM customer);
	
--Top 5 products with highest avg review rating
SELECT "Item Purchased" , avg("Review Rating") as Rating
FROM customer
Group by "Item Purchased"
Order by Rating desc
Limit 5;

--compare the average purchase amounts between standard shipping and express shipping

SELECT 
    "Shipping Type" AS shipping,
    ROUND(AVG("Purchase Amount (USD)"), 2) AS purchase
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

--compare avg spend and total revenue between subscribed and non-subscribed 
SELECT  "Subscription Status" , Round(avg("Purchase Amount (USD)"),2) , Round(sum("Purchase Amount (USD)"),2) 
FROM customer
GROUP BY "Subscription Status"
Order by "Subscription Status" Desc;

--which 5 product have highest percentage of purchases with discount applied 
SELECT "Item Purchased", ROUND(
        (COUNT("Item Purchased")::numeric / 
         (SELECT COUNT("Item Purchased") FROM customer)
        ) * 100, 2
    ) AS percentage_share 
FROM customer
WHERE "Discount Applied" = 'Yes'
GROUP BY "Item Purchased"
ORDER BY percentage_share DESC
LIMIT 5;

select * from customer limit 20;

--Segment customers into loyal , returning , new on the basis of total amount of previous purchases 
--and show count of each segment
SELECT 
    "Customer ID",
    "Previous Purchases",
    CASE 
        WHEN "Previous Purchases" > 25 THEN 'Loyal Customer'
        WHEN "Previous Purchases" > 10 AND "Previous Purchases" <= 25 THEN 'Returning'
        WHEN "Previous Purchases" <= 10 THEN 'NEW'
    END AS customer_category
FROM customer;


--are customers who are repeat buyers also likely to subscribe?
select "Subscription Status" ,
count("Customer ID") as repeat_buyers
from customer 
where "Previous Purchases" > 5
group by "Subscription Status";


--revenue contribution of each age group

SELECT
    age_group,
    age_group_revenue,
    ROUND(
        age_group_revenue * 100.0 /
        (SELECT SUM("Purchase Amount (USD)") FROM customer),
        2
    ) AS revenue_contribution_percent
FROM (
    SELECT
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END AS age_group,
        SUM("Purchase Amount (USD)") AS age_group_revenue
    FROM customer
    GROUP BY
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END
) t
ORDER BY age_group;

SELECT
    age_group,
    age_group_revenue,
    ROUND(
        age_group_revenue * 100.0 /
        (SELECT SUM("Purchase Amount (USD)") FROM your_table_name),
        2
    ) AS revenue_contribution_percent
FROM (
    SELECT
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END AS age_group,
        SUM("Purchase Amount (USD)") AS age_group_revenue
    FROM your_table_name
    GROUP BY
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END
) t
ORDER BY age_group;


SELECT
    age_group,
    age_group_revenue,
    ROUND(
        age_group_revenue * 100.0 /
        (SELECT SUM("Purchase Amount (USD)") FROM your_table_name),
        2
    ) AS revenue_contribution_percent
FROM (
    SELECT
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END AS age_group,
        SUM("Purchase Amount (USD)") AS age_group_revenue
    FROM your_table_name
    GROUP BY
        CASE
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'
            WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END
) t
ORDER BY age_group;


SELECT current_user;










	




